# Generated by Django 3.1.12 on 2022-03-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourwork',
            name='website',
            field=models.TextField(null=True),
        ),
    ]
