# Generated by Django 3.1.12 on 2022-03-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_ourwork_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='image_source',
            field=models.ImageField(blank=True, null=True, upload_to='homepage'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='image_source',
            field=models.ImageField(blank=True, null=True, upload_to='homepage'),
        ),
        migrations.AlterField(
            model_name='ourwork',
            name='image_source',
            field=models.ImageField(blank=True, null=True, upload_to='homepage'),
        ),
    ]
