# Generated by Django 3.1.12 on 2022-03-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='text',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='feature',
            name='elaborate',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='heading',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='svg',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='title',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slogan',
            name='type_effect',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
