# Generated by Django 3.1.12 on 2022-06-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20220319_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slogan', models.TextField(null=True)),
                ('hero_image', models.TextField(null=True)),
                ('about', models.TextField()),
                ('mission', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('geo_coordinates', models.TextField(null=True)),
                ('logo_url', models.TextField(null=True)),
                ('logo_source_url', models.ImageField(blank=True, null=True, upload_to='homepage')),
                ('login_url', models.TextField(null=True)),
                ('seo_keyword', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('svg', models.TextField(blank=True, null=True)),
                ('heading', models.TextField(blank=True, null=True)),
                ('elaborate', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='HeroImage',
        ),
        migrations.DeleteModel(
            name='Slogan',
        ),
    ]
