# Generated by Django 3.1.12 on 2022-06-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20220626_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='instagram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='linkedin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='twitter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
